### ISSUE TITLE
Missing documentation & code examples.

### ISSUE THREAD

**Issue by maciejczyzewski** [vgm64/gmplot#26]

**Comment by alesancoml** [comment]
The sample code is not working.
NameError: name 'latitudes' is not defined

**Comment by alibugra** [comment]
If you define `latitudes = [40.0111111] longitudes = [20.0111111]` with your latitudes, longitudes values, sample code will be working.

**Comment by josepablog** [comment]
Example is not working for me:
```
import gmplot
gmap = gmplot.from_geocode("San Francisco")
```

It returns this error:
```AttributeError: 'module' object has no attribute 'from_geocode'```

How can I make it work?

**Comment by deltawi** [comment]
I have the same issue as @josepablog. Did anyone solve this issue ?

**Comment by maciejczyzewski** [comment]
@deltawi @josepablog 
```
from gmplot import GoogleMapPlotter as gmp
gmap = gmp.from_geocode("San Francisco")
```

**Comment by divesh987** [comment]
@maciejczyzewski Still does not work ...

**Comment by MuqadderIqbal** [comment]
This package is in serious need of thorough documentation on how to get things to work. It also lacks any useful (and working) examples. I've been struggling to plot a marker on a map for an hour now and I'm just giving up at this point. I'm shelving the usage of this library until a good quality documentation is added at some point.

**Comment by vgm64** [comment]
@MuqadderIqbal I've just updated the README with a more full example (err, a real example). Since this package is supposed to be Google Maps plotting "the easy way" I'd am curious about what you tried that didn't work and why you thought to try what you tried. If it all hinged on not having a real example, so be it.

If the new README example gets you going, feel free to provide pull requests with examples that you think others will find useful.

**Comment by MuqadderIqbal** [comment]
@vgm64 Due to the lack of working examples and some more documentation around it, I didn't find the library enabling mapping abilities the easy way. Perhaps with your latest edits, things will seem easier for a new user but I haven't had a chance to review the changes myself. 
The issue(s) I ran in to before giving up are well documented by other users under the Issues section (marker not showing up on map, not even with the examples provided in ReadMe). I see that some work has happened on that front but you haven't merged those changes yet. That's where I gave up too.

I'll give this library another shot when I am able to find some free time and document my observations along the way. If I do get the library to work for my setup, I'll document that as well along with some additional code examples for others to use.

**Comment by vgm64** [comment]
@MuqadderIqbal I'm going to close this issue because it sounds like most of the issue was not having a code snippet that one could copy/paste and generate a functioning map. If you try out the new example and still have issues, feel free to reopen. If you are on Windows and your marker issue seems to be the problem with the path delimiter mentioned in other issue threads, chime in there.

When you say "The issue(s)" I would appreciate you expanding on exactly what you tried. I don't want to guess which issues you're referring to and what your setup/use case/snippets are.
